import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

import { PAGE_META } from './src/data/page-meta.js'

// The project is ESM ("type": "module"), so __dirname does not exist here.
const root = dirname(fileURLToPath(import.meta.url))

// Production is alamasidreamcurtains.com (DigitalOcean App Platform, auto-deployed
// from main), which serves from the domain root - so the base must be '/'.
// Do NOT set this to '/curtain_website/': that is only correct for the secondary
// GitHub Pages copy, and using it here 404s every asset on the live domain.
const PROD_BASE = '/'

// Multi-page build. Vite derives each output path from the input path relative
// to the project root, so `curtains/index.html` lands at `dist/curtains/index.html`
// and serves at `/curtains/`. Those files are generated by `npm run pages`.
const input = {
  main: resolve(root, 'index.html'),
  ...Object.fromEntries(
    PAGE_META.map((page) => [page.slug, resolve(root, page.slug, 'index.html')]),
  ),
}

export default defineConfig(({ command, isPreview }) => ({
  base: command === 'build' || isPreview ? PROD_BASE : '/',
  build: {
    outDir: 'dist',
    rollupOptions: { input },
  },
  plugins: [react()],
}))
